let questions = [
    {
        'question' : 'Wofür ist das Modul am Compound Primär zuständig?',
        'answer_1' : 'Geschwindigkeit',
        'answer_2' : 'Abschussgeräusch dämpfen',
        'answer_3' : 'Auszugslänge',
        'answer_4' : 'indiviuelles Styling',
        'right_answer' : 3,
    },
    {
        'question' : 'Welcher ist kein historischer Bogen?',
        'answer_1' : 'Langbogen',
        'answer_2' : 'Recurve',
        'answer_3' : 'Reiterbogen',
        'answer_4' : 'Compound',
        'right_answer' : 4,
    },
    {
        'question' : 'Wer hält den aktuellen Rekord im Recurve auf 70m mit 702/720?',
        'answer_1' : 'Brady Ellison',
        'answer_2' : 'Mete Gazoz',
        'answer_3' : 'Mauro Nespoli',
        'answer_4' : 'Kim Woojin',
        'right_answer' : 1,
    },
    {
        'question' : 'Wer hält die meisten Rekorde im Recurve aktuell?',
        'answer_1' : 'Brady Ellison',
        'answer_2' : 'Mete Gazoz',
        'answer_3' : 'Mauro Nespoli',
        'answer_4' : 'Kim Woojin',
        'right_answer' : 4,
    },
    {
        'question' : 'Welcher Schütze tritt nicht mit dem Compound an?',
        'answer_1' : 'Mike Schlosser',
        'answer_2' : 'Florian Unruh',
        'answer_3' : 'Braden Gellenthien',
        'answer_4' : 'James Lutz',
        'right_answer' : 2,
    },
    {
        'question' : 'Wie lang darf der Frontstabilisator laut IFAA in der BowHunter Unlimited Klasse sein?',
        'answer_1' : '6Inch',
        'answer_2' : '9Inch',
        'answer_3' : '12Inch',
        'answer_4' : '15Inch',
        'right_answer' : 3,
    },
]